### ISSUE TITLE
Void StartEditing() Error

### ISSUE THREAD

**Issue by disgreen** [haoliangyu/ares#18]
Hello,
Thank you for making this very promising tool available for public use. I have installed the tool as outlined in the README file. When attempting to use the RasterEditor tool to edit a tiff file I get the following error:
Source: StartEditing()
Error: Object Reference Not Set To An Instance of An Object
The file is a tif raster, and is not located in a geodatabase (although I tried it with a geodatabase raster and got the same error).
I'm using ArcGIS 10.3. 
Thank you,
David

**Comment by haoliangyu** [comment]
I am sorry to tell that I am no longer working with ESRI products and this project is kind of not maintained.

A similar problem was solved by recompiling the addon with the latest version of ArcObject. But I am not sure if it would help.
