### ISSUE TITLE
ArcMap 10.3 crashes when saving edited raster

### ISSUE THREAD

**Issue by fonse-ca** [haoliangyu/ares#19]
1. ArcMap crashes every time when pressing the Save Edits button, even if only one pixel was edited. Doesn't matter the raster format, it happens with tif rasters as well. It happens even when problem 2 doesn't happen.
2. After starting an edit session (pressing the Start Edit button), sometimes (not every time) the following error pops up when pressing the Select Edit button.

![erro_ao_carregar_em_select_edit](https://cloud.githubusercontent.com/assets/21334206/18085463/2ead3176-6ea3-11e6-842b-c9fdf2385cde.JPG)

Version:  0.2.1
ArcMap: 10.3.0.4322
Windows 7 Home Premium

**Comment by haoliangyu** [comment]
I am very sorry to tell that I am no longer working with ESRI products and this project is kind of not maintained.
